apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-thanos
  namespace: knative-httpd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keda-operator-token-creator
  namespace: knative-httpd
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    resourceNames:
      - keda-thanos
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-operator-token-creator
  namespace: knative-httpd
subjects:
  - kind: ServiceAccount
    name: keda-operator
    namespace: openshift-keda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-operator-token-creator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-thanos-view
  namespace: openshift-monitoring
subjects:
  - kind: ServiceAccount
    name: keda-thanos
    namespace: knative-httpd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-thanos
  namespace: knative-httpd
spec:
  boundServiceAccountToken:
    - parameter: bearerToken
      serviceAccountName: keda-thanos
