apiVersion: v1
kind: ConfigMap
metadata:
  name: rollouts-canary-blackbox
  namespace: rollouts-canary-demo
data:
  blackbox.yml: |
    modules:
      http_200:
        prober: http
        timeout: 5s
        http:
          method: GET
          valid_status_codes:
            - 200
          follow_redirects: false
          preferred_ip_protocol: ip4
