apiVersion: v1
kind: ConfigMap
metadata:
  name: bookinfo-b-blackbox
  namespace: canary-mesh-full-demo
data:
  blackbox.yml: |
    modules:
      bookinfo_b_candidate:
        prober: http
        timeout: 8s
        http:
          method: GET
          valid_status_codes:
            - 200
          follow_redirects: false
          preferred_ip_protocol: ip4
          fail_if_body_not_matches_regexp:
            - "Book Details"
            - "Book Reviews"
            - "glyphicon glyphicon-star"
            - "text-red-500"
