apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - workloads.yaml
  - service-stable.yaml
  - service-canary.yaml
  - rollout.yaml
  - analysis-template.yaml
  - blackbox-config.yaml
  - blackbox-deployment.yaml
  - blackbox-service.yaml
  - servicemonitor-blackbox.yaml
