apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  namespace: bluegreen-demo
  labels:
    app: bluegreen-app
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bluegreen-app
      version: v2
  template:
    metadata:
      labels:
        app: bluegreen-app
        version: v2
    spec:
      containers:
        - name: app
          image: quay.io/openshifttest/hello-openshift:multiarch
          env:
            - name: RESPONSE
              value: |
                APP VERSION 2
                GREEN deployment
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
