apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-mesh-full-demo-shared
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/gstephan76/argocd-bluegreen.git
    targetRevision: main
    path: full-demo/shared
  destination:
    server: https://kubernetes.default.svc
    namespace: canary-mesh-full-demo
  ignoreDifferences:
    - group: networking.istio.io
      kind: VirtualService
      name: full-demo-router
      namespace: canary-mesh-full-demo
      jqPathExpressions:
        - '.spec.http[] | select(.name == "bookinfo-a-primary") | .route[].weight'
        - '.spec.http[] | select(.name == "bookinfo-b-primary") | .route[].weight'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
