apiVersion: v1
kind: Service
metadata:
  name: metric-ai-kubernetes-agent
  namespace: openshift-gitops
spec:
  selector:
    app: metric-ai-kubernetes-agent
  ports:
    - name: http
      port: 8080
      targetPort: http
