#!/usr/bin/env bash
set -Eeuo pipefail

NAMESPACE="${NAMESPACE:-metric-ai-demo}"
ARGOCD_NAMESPACE="${ARGOCD_NAMESPACE:-openshift-gitops}"
APP_NAME="${APP_NAME:-metric-ai-demo}"
AGENT_NAME="${AGENT_NAME:-metric-ai-kubernetes-agent}"
TIMEOUT_SECONDS="${TIMEOUT_SECONDS:-300}"
POLL_SECONDS="${POLL_SECONDS:-3}"
AUTOFIX_REPO="${AUTOFIX_REPO:-gstephan76/argo-rollouts-quarkus-demo}"
AUTOFIX_BASE_BRANCH="${AUTOFIX_BASE_BRANCH:-main}"
AUTOFIX_BRANCH_PREFIX="${AUTOFIX_BRANCH_PREFIX:-fix/k8s-issue-}"
GITHUB_API_URL="${GITHUB_API_URL:-https://api.github.com}"
AGENT_PR_MARKER="${AGENT_PR_MARKER:-This PR was automatically generated by Kubernetes AI Agent using line-based patches}"

die(){ echo "ERROR: $*" >&2; exit 1; }
for c in oc awk python3; do
  command -v "$c" >/dev/null 2>&1 || die "$c not found"
done

[[ -n "${GITHUB_TOKEN:-}" ]] || \
  die "GITHUB_TOKEN is required by clean-history to clean GitHub auto-fix PRs"

oc whoami >/dev/null 2>&1 || die "Not logged in to OpenShift"

phase="$(oc get rollout "$APP_NAME" -n "$NAMESPACE" -o jsonpath='{.status.phase}' 2>/dev/null || true)"
stable="$(oc get rollout "$APP_NAME" -n "$NAMESPACE" -o jsonpath='{.status.stableRS}' 2>/dev/null || true)"
current="$(oc get rollout "$APP_NAME" -n "$NAMESPACE" -o jsonpath='{.status.currentPodHash}' 2>/dev/null || true)"

[[ "$phase" == "Healthy" && -n "$stable" && "$stable" == "$current" ]] || \
  die "clean-history requires a settled Healthy rollout; run reset first"

echo "==> Cleaning Metric-AI auto-fix pull requests from ${AUTOFIX_REPO}"
AUTOFIX_REPO="$AUTOFIX_REPO" \
AUTOFIX_BASE_BRANCH="$AUTOFIX_BASE_BRANCH" \
AUTOFIX_BRANCH_PREFIX="$AUTOFIX_BRANCH_PREFIX" \
GITHUB_API_URL="$GITHUB_API_URL" \
AGENT_PR_MARKER="$AGENT_PR_MARKER" \
GITHUB_TOKEN="$GITHUB_TOKEN" \
python3 - <<'PY'
import json
import os
import sys
from urllib import error, parse, request

repo = os.environ["AUTOFIX_REPO"]
base_branch = os.environ["AUTOFIX_BASE_BRANCH"]
prefix = os.environ["AUTOFIX_BRANCH_PREFIX"]
marker = os.environ["AGENT_PR_MARKER"]
api_base = os.environ["GITHUB_API_URL"].rstrip("/")
token = os.environ["GITHUB_TOKEN"]

headers = {
    "Accept": "application/vnd.github+json",
    "Authorization": f"Bearer {token}",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "metric-ai-demo-clean-history",
}


def api(method, path, payload=None, allow_missing_ref=False):
    data = None if payload is None else json.dumps(payload).encode("utf-8")
    req = request.Request(
        api_base + path,
        data=data,
        method=method,
        headers=headers,
    )

    try:
        with request.urlopen(req) as response:
            raw = response.read()
            value = json.loads(raw) if raw else None
            return response.status, value
    except error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace").strip()
        if allow_missing_ref:
            if exc.code == 404:
                return 404, None

            if exc.code == 422:
                try:
                    detail = json.loads(raw)
                except json.JSONDecodeError:
                    detail = {}

                if detail.get("message") == "Reference does not exist":
                    return 404, None
        print(
            f"ERROR: GitHub API {method} {path} failed: "
            f"HTTP {exc.code}: {raw}",
            file=sys.stderr,
        )
        raise SystemExit(1)
    except error.URLError as exc:
        print(f"ERROR: GitHub API request failed: {exc}", file=sys.stderr)
        raise SystemExit(1)


pulls = []
page = 1
while True:
    _, batch = api(
        "GET",
        f"/repos/{repo}/pulls?state=all&per_page=100&page={page}",
    )
    if not isinstance(batch, list):
        print("ERROR: unexpected GitHub pull-request response", file=sys.stderr)
        raise SystemExit(1)

    pulls.extend(batch)
    if len(batch) < 100:
        break
    page += 1

candidates = []
for pr in pulls:
    body = pr.get("body") or ""
    head = pr.get("head") or {}
    base = pr.get("base") or {}
    head_repo = (head.get("repo") or {}).get("full_name") or ""
    base_repo = (base.get("repo") or {}).get("full_name") or ""
    head_ref = head.get("ref") or ""
    base_ref = base.get("ref") or ""

    if (
        marker in body
        and head_repo == repo
        and base_repo == repo
        and base_ref == base_branch
        and head_ref.startswith(prefix)
    ):
        candidates.append(pr)

if not candidates:
    print("    no Kubernetes AI Agent auto-fix pull requests found")
    raise SystemExit(0)

candidates = sorted(candidates, key=lambda item: item["number"])

# Close every active Metric-AI PR before cleaning any branch.  This keeps a
# stale historical branch from preventing the current demo PR from being
# closed.
for pr in candidates:
    number = pr["number"]
    state = pr.get("state") or "unknown"
    head_ref = (pr.get("head") or {}).get("ref") or ""

    if state == "open":
        print(f"    closing PR #{number} ({head_ref})")
        api(
            "PATCH",
            f"/repos/{repo}/pulls/{number}",
            {"state": "closed"},
        )
        pr["state"] = "closed"

# Only after all matching open PRs are closed do we clean generated branches.
for pr in candidates:
    number = pr["number"]
    state = pr.get("state") or "unknown"
    merged = bool(pr.get("merged_at"))
    head_ref = (pr.get("head") or {}).get("ref") or ""

    if merged:
        print(f"    PR #{number} already merged; cleaning branch {head_ref}")
    else:
        print(f"    PR #{number} already {state}; cleaning branch {head_ref}")

    encoded_ref = parse.quote(head_ref, safe="/")
    status, _ = api(
        "DELETE",
        f"/repos/{repo}/git/refs/heads/{encoded_ref}",
        allow_missing_ref=True,
    )

    if status == 204:
        print(f"      deleted branch {head_ref}")
    elif status == 404:
        print(f"      branch {head_ref} already absent")
PY

echo "==> Deleting completed AI AnalysisRun history"
oc delete analysisrun \
  -n "$NAMESPACE" \
  --all \
  --ignore-not-found

echo "==> Restarting AI agent to clear its in-memory activity-event store"
oc rollout restart deployment/"$AGENT_NAME" \
  -n "$ARGOCD_NAMESPACE" >/dev/null
oc rollout status deployment/"$AGENT_NAME" \
  -n "$ARGOCD_NAMESPACE" \
  --timeout="${TIMEOUT_SECONDS}s" >/dev/null

desired="$(
  oc get rollout "$APP_NAME" \
    -n "$NAMESPACE" \
    -o jsonpath='{.spec.replicas}' 2>/dev/null || true
)"
[[ "$desired" =~ ^[0-9]+$ && "$desired" -gt 0 ]] || \
  die "Could not determine desired application replica count"

ready_count() {
  oc get pods \
    -n "$NAMESPACE" \
    -l "app=${APP_NAME}" \
    -o jsonpath='{range .items[*]}{range .status.conditions[?(@.type=="Ready")]}{.status}{"\n"}{end}{end}' \
    2>/dev/null |
  awk '$0 == "True" { n++ } END { print n+0 }'
}

pod_count() {
  oc get pods \
    -n "$NAMESPACE" \
    -l "app=${APP_NAME}" \
    -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' \
    2>/dev/null |
  awk 'NF { n++ } END { print n+0 }'
}

wait_for_replicas() {
  deadline=$((SECONDS + TIMEOUT_SECONDS))
  while (( SECONDS < deadline )); do
    total="$(pod_count)"
    ready="$(ready_count)"
    printf '    application pods total=%s ready=%s desired=%s\n' \
      "$total" "$ready" "$desired"
    if (( total >= desired && ready >= desired )); then
      return 0
    fi
    sleep "$POLL_SECONDS"
  done
  return 1
}

echo "==> Recycling dashboard/application pods one at a time"
mapfile -t original_pods < <(
  oc get pods \
    -n "$NAMESPACE" \
    -l "app=${APP_NAME}" \
    --sort-by=.metadata.creationTimestamp \
    -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'
)

for pod in "${original_pods[@]}"; do
  [[ -n "$pod" ]] || continue
  echo "    recycling ${pod}"
  oc delete pod "$pod" \
    -n "$NAMESPACE" \
    --wait=false >/dev/null
  wait_for_replicas || \
    die "Timed out waiting for application replicas after recycling ${pod}"
done

host="$(
  oc get route "$APP_NAME" \
    -n "$NAMESPACE" \
    -o jsonpath='{.spec.host}' 2>/dev/null || true
)"

echo
echo "AI progressive-delivery history cleared."
echo "AnalysisRuns, AI-agent activity memory, and dashboard pod caches were reset."
echo "Metric-AI generated GitHub PRs were closed and their generated branches removed."
echo "GitHub retains closed/merged PR records; those records cannot be deleted by the API."
if [[ -n "$host" ]]; then
  echo "Refresh the browser to clear browser-local graph history:"
  echo "  https://${host}/"
fi
