apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-a-details
  namespace: canary-mesh-multi-bookinfo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-a-ratings
  namespace: canary-mesh-multi-bookinfo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-a-reviews
  namespace: canary-mesh-multi-bookinfo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-a-productpage
  namespace: canary-mesh-multi-bookinfo
---
apiVersion: v1
kind: Service
metadata:
  name: bookinfo-a-details
  namespace: canary-mesh-multi-bookinfo
  labels:
    app.kubernetes.io/part-of: bookinfo
    app.kubernetes.io/instance: bookinfo-a
    app.kubernetes.io/name: details
spec:
  selector:
    app.kubernetes.io/instance: bookinfo-a
    app.kubernetes.io/name: details
  ports:
    - name: http
      port: 9080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-a-details
  namespace: canary-mesh-multi-bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bookinfo-a
      app.kubernetes.io/name: details
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15090"
      labels:
        app.kubernetes.io/part-of: bookinfo
        app.kubernetes.io/instance: bookinfo-a
        app.kubernetes.io/name: details
        app.kubernetes.io/version: v1
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: bookinfo-a-details
      containers:
        - name: details
          image: quay.io/sail-dev/examples-bookinfo-details-v1:1.20.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: bookinfo-a-ratings
  namespace: canary-mesh-multi-bookinfo
  labels:
    app.kubernetes.io/part-of: bookinfo
    app.kubernetes.io/instance: bookinfo-a
    app.kubernetes.io/name: ratings
spec:
  selector:
    app.kubernetes.io/instance: bookinfo-a
    app.kubernetes.io/name: ratings
  ports:
    - name: http
      port: 9080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-a-ratings
  namespace: canary-mesh-multi-bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bookinfo-a
      app.kubernetes.io/name: ratings
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15090"
      labels:
        app.kubernetes.io/part-of: bookinfo
        app.kubernetes.io/instance: bookinfo-a
        app.kubernetes.io/name: ratings
        app.kubernetes.io/version: v1
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: bookinfo-a-ratings
      containers:
        - name: ratings
          image: quay.io/sail-dev/examples-bookinfo-ratings-v1:1.20.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: bookinfo-a-reviews
  namespace: canary-mesh-multi-bookinfo
  labels:
    app.kubernetes.io/part-of: bookinfo
    app.kubernetes.io/instance: bookinfo-a
    app.kubernetes.io/name: reviews
spec:
  selector:
    app.kubernetes.io/instance: bookinfo-a
    app.kubernetes.io/name: reviews
  ports:
    - name: http
      port: 9080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-a-reviews
  namespace: canary-mesh-multi-bookinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bookinfo-a
      app.kubernetes.io/name: reviews
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15090"
      labels:
        app.kubernetes.io/part-of: bookinfo
        app.kubernetes.io/instance: bookinfo-a
        app.kubernetes.io/name: reviews
        app.kubernetes.io/version: v2
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: bookinfo-a-reviews
      containers:
        - name: reviews
          image: quay.io/sail-dev/examples-bookinfo-reviews-v2:1.20.2
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_DIR
              value: /tmp/logs
            - name: RATINGS_HOSTNAME
              value: bookinfo-a-ratings
          ports:
            - name: http
              containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: wlp-output
              mountPath: /opt/ibm/wlp/output
      volumes:
        - name: tmp
          emptyDir: {}
        - name: wlp-output
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: bookinfo-a-productpage
  namespace: canary-mesh-multi-bookinfo
  labels:
    app.kubernetes.io/part-of: bookinfo
    app.kubernetes.io/instance: bookinfo-a
    app.kubernetes.io/name: productpage
spec:
  selector:
    app.kubernetes.io/instance: bookinfo-a
    app.kubernetes.io/name: productpage
  ports:
    - name: http
      port: 9080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-a-productpage
  namespace: canary-mesh-multi-bookinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: bookinfo-a
      app.kubernetes.io/name: productpage
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15090"
      labels:
        app.kubernetes.io/part-of: bookinfo
        app.kubernetes.io/instance: bookinfo-a
        app.kubernetes.io/name: productpage
        app.kubernetes.io/version: v1
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: bookinfo-a-productpage
      containers:
        - name: productpage
          image: quay.io/sail-dev/examples-bookinfo-productpage-v1:1.20.2
          imagePullPolicy: IfNotPresent
          env:
            - name: DETAILS_HOSTNAME
              value: bookinfo-a-details
            - name: REVIEWS_HOSTNAME
              value: bookinfo-a-reviews
            - name: RATINGS_HOSTNAME
              value: bookinfo-a-ratings
          ports:
            - name: http
              containerPort: 9080
          readinessProbe:
            httpGet:
              path: /productpage
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
